version: "3.8"
services:
  valkey:
    image: valkey/valkey:7.2
    ports:
      - "6379:6379"
    command: ["--save", "60", "1", "--appendonly", "yes"]

  keydb:
    image: eqalpha/keydb:latest
    ports:
      - "6380:6379"
    command: ["--save", "60", "1", "--appendonly", "yes"]

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - "6381:6379"
    ulimits:
      memlock: -1

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"

  hazelcast:
    image: hazelcast/hazelcast:5.3
    ports:
      - "5701:5701"

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - VALKEY_URL=redis://valkey:6379
      - KEYDB_URL=redis://keydb:6379
      - DRAGONFLY_URL=redis://dragonfly:6379
      - MEMCACHED_URL=memcached:11211
      - HAZELCAST_URL=hazelcast:5701
    depends_on:
      - valkey
      - keydb
      - dragonfly
      - memcached
      - hazelcast
